allowBuilds:
  better-sqlite3: true
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - electron
  - esbuild
